### ISSUE TITLE
Stuck on survey results page

### ISSUE THREAD

**Issue by kenny-sellers** [DNNCommunity/DNN.Survey#51] opened 2020-10-09 18:20 UTC
## Describe the bug
We have a customer that has this module on their home page. Once a user submits their response for the survey, they can no longer view the home page as it will redirect them to the results page. I did a quick look through the code and I found that the module checks for a cookie and if the person has voted. If so, it directs the user to the results page. To make this work on home pages, this should really be a configuration setting whether to redirect users to the results page if they have voted.

## Software Versions
- DNN: 9.6.2
- Module: 90.00.01

## To Reproduce
Add Module to homepage of site
Add Question to Survey
Submit Vote for Survey
No longer able to access homepage.

**Comment by MaiklT** [comment] 2020-11-07 17:05
This is by design, a user is only allowed to vote once. If you don't want to redirect him to the results page, you can remove the permission to view results from the module permissions. He will then see a message that he has already voted.

**Comment by valadas** [comment] 2020-11-07 19:04
Closing this as it is by design.

**Closed as completed by valadas** 2020-11-07 19:04 UTC
